services:
  backend:
    container_name: reportgri-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Only GPU 1 will be visible inside the container 
  
  nginx:
    depends_on: 
        - backend
    container_name: reportgri-frontend
    build: 
        context: ./frontend/
        dockerfile: Dockerfile
    ports: 
        - "5173:80"
    restart: unless-stopped

