services:
  backend:
    container_name: reportgri-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
  
  nginx:
    depends_on: 
        - backend
    container_name: reportgri-frontend
    build: 
        context: ./frontend/
        dockerfile: Dockerfile
    ports: 
        - "5173:80"
    restart: unless-stopped

